-- UnderWeb OS Identity v1
-- Additive identity layer. Does not replace auth.users IDs or profiles.
begin;

create table if not exists public.underweb_identities (
  user_id uuid primary key references auth.users(id) on delete cascade,
  network_number bigint generated by default as identity unique,
  created_at timestamptz not null default now()
);

alter table public.underweb_identities enable row level security;
revoke all on public.underweb_identities from public, anon, authenticated;

-- Backfill active Owners first so the founding Owner receives the earliest ID.
insert into public.underweb_identities (user_id)
select p.id
from public.profiles p
join public.user_roles ur on ur.user_id = p.id
where ur.status = 'active'
  and lower(ur.role_slug) = 'owner'
  and not exists (
    select 1 from public.underweb_identities ui where ui.user_id = p.id
  )
group by p.id
order by min(ur.granted_at), min(p.created_at);

-- Then backfill every remaining existing profile in profile creation order.
insert into public.underweb_identities (user_id)
select p.id
from public.profiles p
where not exists (
  select 1 from public.underweb_identities ui where ui.user_id = p.id
)
order by p.created_at, p.id;

-- New profiles automatically receive an UnderWeb ID.
create or replace function public.uw_assign_underweb_identity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.underweb_identities (user_id)
  values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

revoke all on function public.uw_assign_underweb_identity()
from public, anon, authenticated;

drop trigger if exists uw_assign_underweb_identity_trg on public.profiles;
create trigger uw_assign_underweb_identity_trg
after insert on public.profiles
for each row execute function public.uw_assign_underweb_identity();

-- Private identity reader for the signed-in account.
create or replace function public.uw_my_identity()
returns table (
  user_id uuid,
  underweb_id text,
  network_number bigint,
  display_name text,
  username text,
  avatar_url text,
  discord_linked boolean,
  vrchat_username text,
  roles text[]
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    p.id,
    'UW-' || lpad(ui.network_number::text, 4, '0'),
    ui.network_number,
    p.display_name,
    p.username,
    p.avatar_url,
    p.discord_user_id is not null,
    p.vrchat_username,
    coalesce(
      array_agg(distinct ur.role_slug) filter (where ur.status = 'active'),
      '{}'::text[]
    )
  from public.profiles p
  join public.underweb_identities ui on ui.user_id = p.id
  left join public.user_roles ur on ur.user_id = p.id
  where p.id = auth.uid()
  group by p.id, ui.network_number;
$$;

revoke all on function public.uw_my_identity() from public, anon;
grant execute on function public.uw_my_identity() to authenticated;

-- Public identity reader respects the existing public_profile flag.
create or replace function public.uw_public_identity(p_user_id uuid)
returns table (
  user_id uuid,
  underweb_id text,
  display_name text,
  username text,
  avatar_url text,
  vrchat_username text,
  roles text[]
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    p.id,
    'UW-' || lpad(ui.network_number::text, 4, '0'),
    p.display_name,
    p.username,
    p.avatar_url,
    p.vrchat_username,
    coalesce(
      array_agg(distinct ur.role_slug) filter (where ur.status = 'active'),
      '{}'::text[]
    )
  from public.profiles p
  join public.underweb_identities ui on ui.user_id = p.id
  left join public.user_roles ur on ur.user_id = p.id
  where p.id = p_user_id
    and p.public_profile is true
  group by p.id, ui.network_number;
$$;

revoke all on function public.uw_public_identity(uuid) from public;
grant execute on function public.uw_public_identity(uuid) to anon, authenticated;

commit;
